# Generated by Django 5.2.9 on 2025-12-23 09:18

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kod/Nomer')),
                ('name', models.CharField(max_length=500, verbose_name='Tovar nomi')),
                ('manufacturer', models.CharField(blank=True, max_length=255, verbose_name='Ishlab chiqaruvchi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tovar',
                'verbose_name_plural': 'Tovarlar (Nomenklatura)',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('revizor', 'Revizor')], default='revizor', max_length=10, verbose_name='Rol')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name="To'liq ism")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='Kim yaratdi')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField(verbose_name='Reviziya raqami')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_progress', 'Jarayonda'), ('completed', 'Tugallangan')], default='pending', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan vaqt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugagan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_revisions', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
            ],
            options={
                'verbose_name': 'Reviziya',
                'verbose_name_plural': 'Reviziyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnaccountedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(blank=True, max_length=100, verbose_name='Seriya')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Yaroqlilik muddati')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Soni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unaccounted_items', to='sklad.product', verbose_name='Tovar')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unaccounted_items', to='sklad.revision', verbose_name='Reviziya')),
                ('revizor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unaccounted_items', to=settings.AUTH_USER_MODEL, verbose_name='Revizor')),
            ],
            options={
                'verbose_name': "Hisobda yo'q tovar",
                'verbose_name_plural': "Hisobda yo'q tovarlar",
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ombor nomi')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
            ],
            options={
                'verbose_name': 'Ombor',
                'verbose_name_plural': 'Omborlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='revision',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='sklad.warehouse', verbose_name='Ombor'),
        ),
        migrations.CreateModel(
            name='RevisionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Tayinlangan'), ('working', 'Ishlayapti'), ('completed', 'Tugatdi')], default='assigned', max_length=20, verbose_name='Status')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='sklad.revision', verbose_name='Reviziya')),
                ('revizor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='Revizor')),
            ],
            options={
                'verbose_name': 'Revizor tayinlash',
                'verbose_name_plural': 'Revizor tayinlashlari',
                'unique_together': {('revision', 'revizor')},
            },
        ),
        migrations.CreateModel(
            name='RevisionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(blank=True, max_length=100, verbose_name='Seriya')),
                ('expiry_date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2050, 12, 31))], verbose_name='Yaroqlilik muddati')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Soni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_items', to='sklad.product', verbose_name='Tovar')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sklad.revision', verbose_name='Reviziya')),
                ('revizor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_items', to=settings.AUTH_USER_MODEL, verbose_name='Revizor')),
            ],
            options={
                'verbose_name': 'Reviziya yozuvi',
                'verbose_name_plural': 'Reviziya yozuvlari',
                'unique_together': {('revision', 'revizor', 'product', 'series', 'expiry_date')},
            },
        ),
        migrations.CreateModel(
            name='RevisionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(blank=True, max_length=100, verbose_name='Seriya')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Yaroqlilik muddati')),
                ('expected_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="1C bo'yicha qoldiq")),
                ('actual_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Haqiqiy qoldiq')),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Farq')),
                ('status', models.CharField(choices=[('correct', "To'g'ri"), ('shortage', 'Kam'), ('excess', "Ko'p")], default='correct', max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_results', to='sklad.product', verbose_name='Tovar')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='sklad.revision', verbose_name='Reviziya')),
                ('revizors', models.ManyToManyField(blank=True, related_name='results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reviziya natijasi',
                'verbose_name_plural': 'Reviziya natijalari',
                'unique_together': {('revision', 'product', 'series', 'expiry_date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='revision',
            unique_together={('warehouse', 'revision_number')},
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(blank=True, max_length=100, verbose_name='Seriya')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Yaroqlilik muddati')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Qoldiq (1C bo'yicha)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='sklad.product', verbose_name='Tovar')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='sklad.warehouse', verbose_name='Ombor')),
            ],
            options={
                'verbose_name': "Tovar qoldig'i",
                'verbose_name_plural': 'Tovar qoldiqlari (1C)',
                'unique_together': {('warehouse', 'product', 'series', 'expiry_date')},
            },
        ),
    ]
